// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceEngineeringApi.Data;

#nullable disable

namespace RaceEngineeringApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaceEngineeringApi.Models.Lap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<double>("LapTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("PredictedLapTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("StintId")
                        .HasColumnType("integer");

                    b.Property<int>("TyreLife")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StintId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("RaceEngineeringApi.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RaceEngineeringApi.Models.Stint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Compound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("StintNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Stints");
                });

            modelBuilder.Entity("RaceEngineeringApi.Models.Lap", b =>
                {
                    b.HasOne("RaceEngineeringApi.Models.Stint", "Stint")
                        .WithMany("Laps")
                        .HasForeignKey("StintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stint");
                });

            modelBuilder.Entity("RaceEngineeringApi.Models.Stint", b =>
                {
                    b.HasOne("RaceEngineeringApi.Models.Session", "Session")
                        .WithMany("Stints")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RaceEngineeringApi.Models.Session", b =>
                {
                    b.Navigation("Stints");
                });

            modelBuilder.Entity("RaceEngineeringApi.Models.Stint", b =>
                {
                    b.Navigation("Laps");
                });
#pragma warning restore 612, 618
        }
    }
}
